const char *advice_list[] = {
"Hey Dr. Heartbreaker, got any cures for falling head over heels?",
"Mei-Mei, your smile is more refreshing than mountain air!",
"Is your medical degree in being irresistible?",
"I hear you climb mountains, but you've already reached the peak of cuteness",
"Dr. Tanuwijaya, I think I need a check-up for butterflies in my stomach",
"Mei-Mei, are you a trail? Because I'd follow you anywhere",
"Your bedside manner is giving me palpitations",
"Is hiking your second favorite cardio after making hearts race?",
"Dr. Mei-Mei, your presence is better than any medicine",
"You must be an expert in anatomy, because you've got my heart all figured out",
"Mei-Mei, are you a mountain view? Because you're breathtaking",
"I think I need a doctor's note to excuse me from falling for you",
"Your hiking boots must be magic, they've walked right into my heart",
"Dr. Tanuwijaya, is flirtation covered by my insurance?",
"Mei-Mei, you've scaled the heights of charm!",
"Is your stethoscope picking up the sound of my heart skipping a beat?",
"You must be in great shape from carrying around all that medical knowledge",
"Mei-Mei, your smile could light up the darkest hiking trail",
"Dr. Heartstealer, what's your prescription for a crush?",
"You've hiked your way to the summit of my affections",
"Mei-Mei, is your medical specialty in being adorable?",
"I think I need a check-up, I can't stop thinking about you",
"Your bedside manner is making me weak in the knees",
"Dr. Tanuwijaya, you're the cure for a dull day",
"Mei-Mei, are you a compass? Because you're guiding me to happiness",
"Is your medical coat designer? Because you make it look so good",
"You must be tired from running through my mind all day",
"Dr. Mei-Mei, your intelligence is as attractive as your smile",
"I'd climb any mountain to see that gorgeous face",
"Mei-Mei, did it hurt when you fell from the top of that hiking trail?",
"Your diagnosis: Chronic cuteness overload",
"Dr. Tanuwijaya, I think I'm allergic to your charm",
"Mei-Mei, you've got the perfect balance of brains and beauty",
"Is your hiking backpack full of stolen hearts?",
"Dr. Heartbreaker, got any band-aids? You've got me falling for you",
"Mei-Mei, your energy could power a whole hospital",
"Your medical knowledge is impressive, but your charm is off the charts",
"I'd trade all the mountain views just to see your smile",
"Dr. Tanuwijaya, is flirting a form of preventative medicine?",
"Mei-Mei, you must be exhausted from running through my dreams all night",
"Your bedside manner is making my heart rate spike",
"Dr. Mei-Mei, I think I need a prescription for more of your company",
"Is your hiking trail rated difficult? Because you're hard to get over",
"Mei-Mei, your laughter is more refreshing than a mountain stream",
"Dr. Tanuwijaya, I think I'm coming down with a case of the butterflies",
"You must be a great doctor, you've already cured my boredom",
"Mei-Mei, are you a rare plant? Because you're one of a kind",
"Your medical skills are impressive, but your charm is the real lifesaver",
"Dr. Heartstealer, what's the treatment for being lovestruck?",
"Mei-Mei, you've reached the peak of adorableness",
"Is your stethoscope picking up how fast you make my heart beat?",
"Dr. Tanuwijaya, I might need CPR after seeing your smile",
"Mei-Mei, you must be a pro at taking pulses, because you've got mine racing",
"Your hiking boots must be made for walking into people's hearts",
"Dr. Mei-Mei, is charm one of your medical specialties?",
"I'd brave any treacherous trail just to spend time with you",
"Mei-Mei, your personality is as refreshing as mountain air",
"Dr. Tanuwijaya, I think I need a second opinion on how cute you are",
"Is your medical coat magical? Because you've cast a spell on me",
"Mei-Mei, you must be tired from climbing to the top of my mind",
"Your bedside manner is giving me a chronic case of the smiles",
"Dr. Heartbreaker, what's your remedy for being head over heels?",
"Mei-Mei, you've conquered the mountain of my affections",
"Is your medical degree in being irresistibly charming?",
"Dr. Tanuwijaya, I think I need a check-up for these fuzzy feelings",
"Mei-Mei, are you a compass? Because you're pointing me towards happiness",
"Your hiking skills must be top-notch, you've navigated right to my heart",
"Dr. Mei-Mei, is there a cure for being smitten?",
"I'd follow your trail markers anywhere",
"Mei-Mei, your smile could light up the darkest hospital corridor",
"Dr. Tanuwijaya, I think I'm allergic to how adorable you are",
"Is your backpack heavy? It must be full of admirers",
"Mei-Mei, you've scaled the heights of cuteness",
"Your medical knowledge is impressive, but your wit is the real showstopper",
"Dr. Heartstealer, got any treatments for a racing heart?",
"Mei-Mei, are you a rare medicinal plant? Because you're one in a million",
"Is your hiking pace always this heart-racing?",
"Dr. Tanuwijaya, I think I need a prescription for more of your jokes",
"Mei-Mei, your charm could move mountains",
"Your stethoscope must be broken, it's not picking up how hard I've fallen",
"Dr. Mei-Mei, is being delightful one of your side effects?",
"I'd brave any medical procedure just to see your smile",
"Mei-Mei, you must be an expert in matters of the heart",
"Dr. Tanuwijaya, I think I need a referral to the department of admirers",
"Is your hiking trail rated 'Extremely Charming'?",
"Mei-Mei, your personality is as uplifting as reaching a mountain peak",
"Dr. Heartbreaker, what's your diagnosis for these butterflies?",
"Your medical skills are impressive, but your charisma is the real lifesaver",
"Mei-Mei, are you a rare species? Because you're truly one of a kind",
"Is your lab coat designer? Because you make it look so good",
"Dr. Tanuwijaya, I might need oxygen after you take my breath away",
"Mei-Mei, you must be a pro at taking heart rates, you've got mine racing",
"Your hiking boots must be magic, they've walked right into my dreams",
"Dr. Mei-Mei, is being adorable covered by my insurance?",
"I'd climb any medical textbook mountain to impress you",
"Mei-Mei, your smile is more rejuvenating than a day in nature",
"Dr. Tanuwijaya, I need a second opinion on how wonderful you are",
"Is your medical coat enchanted? Because you've cast a spell on me",
"Mei-Mei, you must be tired from running through my thoughts all day",
"Your bedside manner is giving me a chronic case of happiness",
"Dr. Heartstealer, what's your prescription for being lovestruck?",
 "Mei-Mei, you've reached the summit of charm",
 "Is your medical degree in being unforgettably cute?",
 "Dr. Tanuwijaya, I need a check-up for these warm fuzzy feelings",
 "Mei-Mei, are you a trail map? You're guiding me to joy",
 "Your hiking skills are incredible, you've navigated to my affections",
 "Dr. Mei-Mei, is there a treatment for being totally enchanted?",
 "I'd follow your medical advice anywhere",
 "Mei-Mei, your laughter could brighten up any emergency room",
 "Dr. Tanuwijaya, I'm coming down with a case of the smittens",
 "Is your backpack full of stolen hearts from fellow hikers?",
 "Mei-Mei, you've climbed to the peak of adorableness",
 "Your medical expertise is impressive, but your personality is the real cure",
 "Dr. Heartbreaker, got remedies for feeling weak in the knees?",
 "Mei-Mei, are you a rare medical discovery? You're priceless",
 "Is your hiking pace always this heart-fluttering?",
 "Dr. Tanuwijaya, I need a prescription for more of your company",
 "Mei-Mei, your charm could move medical mountains",
 "Your stethoscope must be broken, it's not detecting how hard I've fallen",
 "Dr. Mei-Mei, is being utterly delightful one of your specialties?",
 "I'd face any medical procedure just to see that beautiful smile",
 "Mei-Mei, you're an expert in cardiac care, you've captured my heart",
 "Dr. Tanuwijaya, I need a referral to the department of admirers",
 "Is your favorite hiking trail called 'Stealing Hearts'?",
 "Mei-Mei, your energy is as invigorating as reaching a mountain summit",
 "Dr. Heartbreaker, what's your diagnosis for these fluttering feelings?",
 "Your medical skills impress, but your charm is the true healing power",
 "Mei-Mei, are you a rare species of doctor? You're truly exceptional",
 "Is your lab coat enchanted? You look magical in it",
 "Dr. Tanuwijaya, I need medical attention after you take my breath away",
 "Mei-Mei, you're a cardiology expert, you've got my heart racing",
 "Your hiking boots are special, they've walked right into my affections",
 "Dr. Mei-Mei, is being irresistible part of your medical training?",
 "I'd study any medical textbook just to talk with you",
 "Mei-Mei, your presence is more refreshing than a cool mountain breeze",
 "Dr. Tanuwijaya, I need an examination of these feelings for you",
 "Is your medical coat made of boyfriend material?",
 "Mei-Mei, you must be tired from hiking through my daydreams",
 "Your bedside manner is giving me a severe case of admiration",
 "Dr. Heartstealer, what's your prescription for a racing pulse?",
 "Mei-Mei, you've scaled the heights of my esteem",
 "Is your medical degree in being unforgettably charming?",
 "Dr. Tanuwijaya, I need a check-up for this rapid heartbeat",
 "Mei-Mei, are you a GPS? You're always leading me to happiness",
 "Your trail-blazing skills are top-notch, you've found a path to my heart",
 "Dr. Mei-Mei, is there a cure for being completely captivated?",
 "I'd follow your medical lectures anywhere",
 "Mei-Mei, your smile could power an entire hospital",
 "Dr. Tanuwijaya, I'm experiencing symptoms of major attraction",
 "Is your backpack full of medical marvels and stolen hearts?",
 "Mei-Mei, you've ascended to the apex of allure",
 "Your medical knowledge impresses, but your wit is the real remedy",
 "Dr. Heartbreaker, got treatments for butterflies in the stomach?",
 "Mei-Mei, are you a medical miracle? You're simply incredible",
 "Is your hiking tempo always this pulse-quickening?",
 "Dr. Tanuwijaya, I need a prescription for daily doses of your charm",
 "Mei-Mei, your appeal could revolutionize medical science",
 "Your stethoscope must be faulty, it's not registering my skipping heart",
 "Dr. Mei-Mei, is being absolutely delightful part of your medical oath?",
 "I'd conquer any medical challenge just to earn your admiration",
 "Mei-Mei, you're a master of hearts, both medical and romantic",
 "Dr. Tanuwijaya, I need a referral to the specialist of your affections",
 "Is your favorite hiking path the 'Trail of Enchantment'?",
 "Mei-Mei, your spirit is as uplifting as conquering the toughest mountain",
 "Dr. Heartbreaker, what's your diagnosis for this chronic admiration?",
 "Mei-Mei, is your smile powered by sunbeams?",
 "Do you have a map? I keep getting lost in your eyes",
 "Melyana, you must be a magician, everyone disappears when you're around",
 "Is your name Wi-Fi? Because I'm really feeling a connection",
 "Mei-Mei, are you made of copper and tellurium? You're Cu-Te",
 "Melyana, got a Band-Aid? I scraped my knee falling for you",
 "Are you a camera? Every time I look at you, I smile",
 "Mei-Mei, is your dad a boxer? You're a knockout!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, are you a parking ticket? You've got 'Fine' written all over you",
 "Mei-Mei, I'm no photographer, but I can picture us together",
 "Is there a rainbow today? I just found the treasure I've been searching for",
 "Melyana, are you a bank loan? You've got my interest",
 "Mei-Mei, do you have a sunburn, or are you always this hot?",
 "Are you religious? You're the answer to all my prayers",
 "Melyana, is your name Google? You've got everything I've been searching for",
 "Mei-Mei, are you a time traveler? I see you in my future",
 "Do you have a name, or can I call you mine?",
 "Melyana, if being cute was a crime, you'd be guilty as charged",
 "Mei-Mei, are you an alien? You're out of this world",
 "Is something wrong with my eyes? I can't take them off you",
 "Melyana, do you have a map? I keep getting lost in your eyes",
 "Mei-Mei, are you a campfire? You're hot and I want s'more",
 "Are you a magician? When I look at you, everyone else disappears",
 "Melyana, got a pencil? I want to erase your past and write our future",
 "Mei-Mei, are you a parking ticket? You've got FINE written all over you",
 "Is this the Hogwarts Express? It feels like we're headed somewhere magical",
 "Melyana, are you a bank loan? You have my interest!",
 "Mei-Mei, got a Band-Aid? I scraped my knee falling for you",
 "Are you a time traveler? I see you in my future!",
 "Melyana, if you were a vegetable you'd be a cute-cumber!",
 "Mei-Mei, are you French? Because Eiffel for you",
 "Do you have a map? I keep getting lost in your eyes",
 "Melyana, are you a camera? Every time I look at you, I smile",
 "Mei-Mei, do you have a name or can I call you mine?",
 "Are you a parking ticket? You've got FINE written all over you",
 "Melyana, if being cute was a crime, you'd be guilty as charged!",
 "Mei-Mei, are you a fruit? Because you're a fine-apple!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, are you a magician? Everyone else disappears when I look at you",
 "Mei-Mei, do you have a sunburn, or are you always this hot?",
 "Are you religious? Because you're the answer to all my prayers",
 "Melyana, is your name Wi-Fi? Because I'm really feeling a connection",
 "Mei-Mei, are you a camera? Because every time I look at you, I smile",
 "Do you have a map? I just keep getting lost in your eyes",
 "Melyana, are you a parking ticket? You've got 'Fine' written all over you",
 "Mei-Mei, if you were a vegetable, you'd be a cute-cumber!",
 "Are you a time traveler? Because I see you in my future",
 "Melyana, want a pencil? I'll erase your past and write our future",
 "Mei-Mei, are you made of copper and tellurium? Because you're Cu-Te",
 "Is your dad a boxer? Because you're a knockout!",
 "Melyana, are you a campfire? Because you're hot and I want s'more",
 "Mei-Mei, need a Band-Aid? I just scraped my knee falling for you",
 "Are you a bank loan? Because you've got my interest",
 "Melyana, are you Google? You've got everything I've been searching for",
 "Mei-Mei, are you a fruit? Because you're a fine-apple!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, if being cute was a crime, you'd be guilty as charged",
 "Mei-Mei, are you an interior decorator? The room became beautiful",
 "Is there an airport nearby or is that just my heart taking off?",
 "Melyana, are you a loan? Because you've got my interest!",
 "Mei-Mei, do you have a map? I keep getting lost in your eyes",
 "Are you a magician? Everyone else disappears when I look at you",
 "Melyana, if you were a vegetable you'd be a cute-cumber!",
 "Mei-Mei, are you French? Because Eiffel for you",
 "Do you have a name or can I call you mine?",
 "Melyana, are you a camera? Every time I look at you, I smile",
 "Mei-Mei, if being cute was a crime, you'd be guilty as charged!",
 "Are you a parking ticket? You've got FINE written all over you",
 "Melyana, do you have a sunburn, or are you always this hot?",
 "Mei-Mei, are you religious? You're the answer to all my prayers",
 "Is your name Wi-Fi? Because I'm really feeling a connection",
 "Melyana, are you a fruit? Because you're a fine-apple!",
 "Mei-Mei, do you believe in love at first sight, or should I walk by again?",
 "Are you a magician? Everyone else disappears when I look at you",
 "Melyana, want a pencil? I'll erase your past and write our future",
 "Mei-Mei, are you made of copper and tellurium? Because you're Cu-Te",
 "Is your dad a boxer? Because you're a knockout!",
 "Melyana, are you a campfire? Because you're hot and I want s'more",
 "Mei-Mei, need a Band-Aid? I just scraped my knee falling for you",
 "Are you a bank loan? Because you've got my interest",
 "Melyana, are you Google? You've got everything I've been searching for",
 "Mei-Mei, are you a time traveler? Because I see you in my future",
 "Do you have a name, or can I call you mine?",
 "Melyana, if being cute was a crime, you'd be guilty as charged",
 "Mei-Mei, are you an alien? Because you're out of this world",
 "Is there something wrong with my eyes? I can't take them off you",
 "Melyana, do you have a map? I just keep getting lost in your eyes",
 "Mei-Mei, are you a parking ticket? You've got FINE written all over you",
 "Is this the Hogwarts Express? We're headed somewhere magical",
 "Melyana, are you a loan? Because you have my interest!",
 "Mei-Mei, need a Band-Aid? I just scraped my knee falling for you",
 "Are you a time traveler? Cause I see you in my future!",
 "Melyana, if you were a vegetable you'd be a cute-cumber!",
 "Mei-Mei, are you French? Because Eiffel for you",
 "Do you have a map? I keep getting lost in your eyes",
 "Melyana, are you a camera? Every time I look at you, I smile",
 "Mei-Mei, do you have a name or can I call you mine?",
 "Are you a parking ticket? You've got FINE written all over you",
 "Melyana, if being cute was a crime, you'd be guilty as charged!",
 "Mei-Mei, are you a fruit? Because you're a fine-apple!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, are you a magician? Everyone else disappears when I look at you",
 "Mei-Mei, do you have a sunburn, or are you always this hot?",
 "Are you religious? Because you're the answer to all my prayers",
 "Melyana, is your name Wi-Fi? Because I'm really feeling a connection",
 "Mei-Mei, are you a camera? Every time I look at you, I smile",
 "Do you have a map? I just keep getting lost in your eyes",
 "Melyana, are you a parking ticket? You've got 'Fine' written all over you",
 "Mei-Mei, if you were a vegetable, you'd be a cute-cumber!",
 "Are you a time traveler? Because I see you in my future",
 "Melyana, want a pencil? I'll erase your past and write our future",
 "Mei-Mei, are you made of copper and tellurium? Because you're Cu-Te",
 "Is your dad a boxer? Because you're a knockout!",
 "Melyana, are you a campfire? Because you're hot and I want s'more",
 "Mei-Mei, need a Band-Aid? I just scraped my knee falling for you",
 "Are you a bank loan? Because you've got my interest",
 "Melyana, are you Google? You've got everything I've been searching for",
 "Mei-Mei, are you a fruit? Because you're a fine-apple!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, if being cute was a crime, you'd be guilty as charged",
 "Mei-Mei, are you an interior decorator? The room became beautiful",
 "Is there an airport nearby or is that just my heart taking off?",
 "Melyana, are you a loan? Because you've got my interest!",
 "Mei-Mei, do you have a map? I keep getting lost in your eyes",
 "Are you a magician? Everyone else disappears when I look at you",
 "Melyana, if you were a vegetable you'd be a cute-cumber!",
 "Mei-Mei, are you French? Because Eiffel for you",
 "Do you have a name or can I call you mine?",
 "Melyana, are you a camera? Every time I look at you, I smile",
 "Mei-Mei, if being cute was a crime, you'd be guilty as charged!",
 "Are you a parking ticket? You've got FINE written all over you",
 "Melyana, do you have a sunburn, or are you always this hot?",
 "Mei-Mei, are you religious? You're the answer to all my prayers",
 "Is your name Wi-Fi? Because I'm really feeling a connection",
 "Melyana, are you a fruit? Because you're a fine-apple!",
 "Mei-Mei, do you believe in love at first sight, or should I walk by again?",
 "Are you a magician? Everyone else disappears when I look at you",
 "Melyana, do you have a pencil? I want to erase your past and write our future",
 "Mei-Mei, are you made of copper and tellurium? Because you're Cu-Te",
 "Is your dad a boxer? Because you're a knockout!",
 "Melyana, are you a campfire? Because you're hot and I want s'more",
 "Mei-Mei, do you have a Band-Aid? I just scraped my knee falling for you",
 "Are you a bank loan? Because you've got my interest",
 "Melyana, is your name Google? You've got everything I've been searching for",
 "Mei-Mei, are you a time traveler? Because I see you in my future",
 "Do you have a name, or can I call you mine?",
 "Melyana, if being cute was a crime, you'd be guilty as charged",
 "Mei-Mei, are you an alien? Because you're out of this world",
 "Is there something wrong with my eyes? I can't take them off you",
 "Melyana, do you have a map? I just keep getting lost in your eyes",
 "Mei-Mei, are you a parking ticket? You've got FINE written all over you",
 "Is this the Hogwarts Express? It feels like we're headed somewhere magical",
 "Melyana, are you a loan? Because you have my interest!",
 "Mei-Mei, do you have a Band-Aid? I just scraped my knee falling for you",
 "Are you a time traveler? Cause I see you in my future!",
 "Melyana, if you were a vegetable you'd be a cute-cumber!",
 "Mei-Mei, are you French? Because Eiffel for you",
 "Do you have a map? I keep getting lost in your eyes",
 "Melyana, are you a camera? Because every time I look at you, I smile",
 "Mei-Mei, do you have a name or can I call you mine?",
 "Are you a parking ticket? Because you've got FINE written all over you",
 "Melyana, if being cute was a crime, you'd be guilty as charged!",
 "Mei-Mei, are you a fruit? Because you're a fine-apple!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, are you a magician? When I look at you, everyone else disappears",
 "Mei-Mei, do you have a sunburn, or are you always this hot?",
 "Are you religious? Because you're the answer to all my prayers",
 "Melyana, is your name Wi-Fi? Because I'm really feeling a connection",
 "Mei-Mei, are you a camera? Because every time I look at you, I smile",
 "Do you have a map? I just keep getting lost in your eyes",
 "Melyana, are you a parking ticket? You've got 'Fine' written all over you",
 "Mei-Mei, if you were a vegetable, you'd be a cute-cumber!",
 "Are you a time traveler? Because I see you in my future",
 "Melyana, do you have a pencil? I want to erase your past and write our future",
 "Mei-Mei, are you made of copper and tellurium? Because you're Cu-Te",
 "Is your dad a boxer? Because you're a knockout!",
 "Melyana, are you a campfire? Because you're hot and I want s'more",
 "Mei-Mei, do you have a Band-Aid? I just scraped my knee falling for you",
 "Are you a bank loan? Because you've got my interest",
 "Melyana, is your name Google? You've got everything I've been searching for",
 "Mei-Mei, are you a fruit? Because you're a fine-apple!",
 "Do you believe in love at first sight, or should I walk by again?",
 "Melyana, if being cute was a crime, you'd be guilty as charged",
 "Mei-Mei, are you an interior decorator? The room became beautiful when I saw you",
 "Is there an airport nearby or is that just my heart taking off?",
 "Melyana, are you a loan? Because you've got my interest!",
 "Mei-Mei, do you have a map? I keep getting lost in your eyes",
 "Are you a magician? When I look at you, everyone else disappears",
 "Melyana, if you were a vegetable you'd be a cute-cumber!",
 "Mei-Mei, are you French? Because Eiffel for you",
 "Do you have a name or can I call you mine?",
 "Melyana, are you a camera? Because every time I look at you, I smile",
 "Mei-Mei, if being cute was a crime, you'd be guilty as charged!",
 "Are you a parking ticket? Because you've got FINE written all over you",
 "Melyana, do you have a sunburn, or are you always this hot?",
 "Mei-Mei, are you religious? Because you're the answer to all my prayers",
 "Is your name Wi-Fi? Because I'm really feeling a connection",
 "Melyana, are you a fruit? Because you're a fine-apple!",
 "Mei-Mei, do you believe in love at first sight, or should I walk by again?",
 "Are you a magician? When I look at you, everyone else disappears",
 "Melyana, do you have a pencil? I want to erase your past and write our future",
 "Mei-Mei, are you made of copper and tellurium? Because you're Cu-Te",
 "Is your dad a boxer? Because you're a knockout!",
 "Melyana, are you a campfire? Because you're hot and I want s'more",
 "Mei-Mei, do you believe in love at first sight, or should I walk by again?",
 "Just thinking about you makes my day brighter, Mei-Mei.",
 "Mei-Mei, if I had a flower for every thought of you, I'd walk in my garden forever",
 "Hey Melyana, do you have a map? I keep getting lost in your eyes.",
 "Mei-Mei, are you a magician? When I look at you, everyone else disappears.",
 "Melyana, if beauty were a crime, you'd be serving a life sentence.",
 "Hey Mei-Mei, can you lend me a kiss? I promise I'll give it back.",
 "Is the world a little brighter when you're around, Mei-Mei?",
 "Melyana, if I could rearrange the alphabet, I'd put 'U' and 'I' together.",
 "Every time I see you, Mei-Mei, I feel like the luckiest person in the world.",
 "Mei-Mei, do you have a Band-Aid? I just scraped my knee falling for you.",
 "Melyana, are you made of copper and tellurium? Because you're Cu-Te.",
 "Hey Mei-Mei, I must be a snowflake, because I've fallen for you.",
 "Is it hot in here, or is it just you, Mei-Mei?",
 "Mei-Mei, do you have a name, or can I call you mine?",
 "Every moment with you, Melyana, feels like a dream I never want to wake from.",
 "Hey Mei-Mei, are you a time traveler? Because I can see you in my future.",
 "Melyana, I must be a photographer, because I can picture us together.",
 "Mei-Mei, if you were a vegetable, you'd be a cute-cumber.",
 "Hey Mei-Mei, you must be tired, you've been running through my mind all day.",
 "Melyana, your smile must be a black hole, because it's irresistibly attractive.",
 "Do you have a sunburn, Mei-Mei, or are you always this hot?",
 "Mei-Mei, if I asked you out, would your answer be the same as to this question?",
 "Melyana, do you have a pencil? I want to erase your past and write our future.",
 "Is your name Google, Mei-Mei? You've got everything I've been searching for.",
 "Mei-Mei, you must be a parking ticket, you've got 'FINE' written all over you.",
 "Hey Melyana, did it hurt when you fell from heaven?",
 "Mei-Mei, you're like a dictionary – you add meaning to my life.",
 "Do you have a compass, Mei-Mei? Because without you, I'm lost.",
 "Melyana, if kisses were snowflakes, I'd send you a blizzard.",
 "Hey Mei-Mei, are you an angel? Because you've got heavenly vibes.",
 "Every time you smile, Melyana, my heart skips a beat.",
 "Mei-Mei, do you believe in fate? Because I think we were meant to meet.",
 "Hey Mei-Mei, if stars were wishes, I'd wish for you every night.",
"Do you have Wi-Fi, Melyana? Because I'm feeling a connection.",
"Mei-Mei, if you were a book, you'd be a bestseller.",
"Your eyes are like the ocean, Mei-Mei; I could get lost in them forever.",
"Hey Mei-Mei, are you a campfire? You bring warmth and light into my life.",
"Melyana, you make my heart race without even trying.",
"Every time I see you, Mei-Mei, I smile a little more.",
"Mei-Mei, you light up my world like nobody else.",
"Hey Mei-Mei, you must be a magician, everything else disappears around you.",
"Your laughter is like music to my ears, Mei-Mei.",
"Melyana, I think you stole my heart, but you can keep it.",
"Hey Mei-Mei, you're the reason I look forward to tomorrow.",
"Mei-Mei, if you were a dream, I'd never want to wake up.",
"Melyana, every moment with you feels like magic.",
"Mei-Mei, you must be a star, you light up my darkest nights.",
"Hey Mei-Mei, if beauty were a planet, you'd be the whole galaxy.",
"Your smile, Mei-Mei, could melt the iciest of hearts.",
"Melyana, are you a camera? Because every time I look at you, I smile.",
"Mei-Mei, you must be a light switch, because you turn me on.",
"Hey Mei-Mei, did it hurt when you fell from heaven?",
"Mei-Mei, do you have a Band-Aid? I just scraped my heart falling for you.",
"Melyana, every time I see you, I fall a little more in love.",
"Mei-Mei, if we were stars, I'd want to orbit around you forever.",
"Your presence, Mei-Mei, makes my day extraordinary.",
"Hey Mei-Mei, I must be a treasure hunter, because I found you, a gem.",
"Mei-Mei, do you have a map? Because I'm lost in your eyes.",
"Melyana, you're the song I want to listen to on repeat forever.",
"Mei-Mei, if my love for you were a number, it would be infinite.",
"Hey Mei-Mei, do you believe in magic? Everything feels magical with you.",
"Melyana, you're like a ray of sunshine on a cloudy day.",
"Mei-Mei, every time I see you, my heart does a little dance.",
"Mei-Mei, you make the ordinary moments extraordinary.",
"Melyana, your smile is my favorite sunrise.",
"Hey Mei-Mei, are you a wizard? I feel enchanted when I'm with you.",
"Mei-Mei, if love were a storybook, we'd have the perfect ending.",
"Hey Mei-Mei, you must be a thief, because you stole my heart.",
"Melyana, you're the reason I wake up with a smile.",
"Mei-Mei, do you have a Band-Aid? I scraped my knee falling for you.",
"Hey Mei-Mei, are you an angel? Because you've got heavenly vibes.",
"Melyana, every moment with you feels like a beautiful dream.",
"Mei-Mei, you must be a camera because you make me smile.",
"Hey Mei-Mei, do you have a sunburn, or are you always this hot?",
"Melyana, if kisses were snowflakes, I'd send you a blizzard.",
"Mei-Mei, you make my heart race without even trying.",
"Hey Mei-Mei, if you were a vegetable, you'd be a cute-cumber.",
"Melyana, are you a magician? Everything else disappears around you.",
"Mei-Mei, you must be a parking ticket, you've got 'FINE' written all over.",
"Hey Mei-Mei, if stars were wishes, I'd wish for you every night.",
"Melyana, do you have Wi-Fi? Because I'm feeling a connection.",
"Mei-Mei, if you were a book, you'd be a bestseller.",
"Hey Mei-Mei, are you a campfire? You bring warmth and light to my life.",
"Melyana, you make my heart race like nothing else.",
"Mei-Mei, every time I see you, I smile a little more.",
"Mei-Mei, you're the reason I look forward to tomorrow.",
"Mei-Mei, you must be a light switch, because you turn me on.",
"Hey Mei-Mei, did it hurt when you fell from heaven?",
"Mei-Mei, do you have a Band-Aid? I just scraped my heart falling for you.",
"Melyana, every moment with you feels like a beautiful dream.",
"Mei-Mei, you're the melody I can't get out of my head.",
"Hey Mei-Mei, if beauty were a sport, you'd win gold.",
"Melyana, if you were a dessert, you'd be a sweet treat.",
"Mei-Mei, every time I see you, my heart skips a beat.",
"Hey Mei-Mei, you must be an artist, you make my life a masterpiece.",
"Mei-Mei, if you were a flower, you'd be a perfect rose.",
"Melyana, do you have a name, or can I call you mine?",
"Mei-Mei, are you a time traveler? Because I can see you in my future.",
"Mei-Mei, if I had a flower for every thought of you, I'd walk in my garden forever.",
"You've got this, Mei-Mei!",
"Believe in yourself, Melyana",
"Mei-Mei, your medical skills heal my heart too",
"Dr. Tanuwijaya, I need a prescription for your company",
"Hiking with you, Mei-Mei, is the best cardio for my heart",
"Melyana, your bedside manner gives me butterflies",
"Dr. Mei-Mei, your smile is more effective than any medicine",
"Melyana, let's explore new heights together - both medical and mountain",
"Mei-Mei, your diagnosis: chronic cuteness",
"Dr. Tanuwijaya, your charm is off the medical charts",
"Melyana, you're the perfect trail mix of brains and beauty",
"Mei-Mei, your medical coat looks designer on you",
"Dr. Tanuwijaya, I think I'm allergic to your absence",
"Melyana, your energy could power a whole hospital",
"Mei-Mei, got any treatments for falling head over heels?",
"Dr. Tanuwijaya, your presence is better than any vitamin",
"Melyana, you've reached the peak of adorableness",
"Mei-Mei, your laughter is the best medicine",
"Dr. Tanuwijaya, I need a check-up for these heart palpitations",
"Melyana, your smile could light up the darkest hiking trail",
"Mei-Mei, you make my heart rate spike in the best way",
"Dr. Tanuwijaya, your charm is a medical marvel",
"Mei-Mei, your bedside manner's as smooth as your hiking trails",
"Dr. Tanuwijaya, you've diagnosed my heart with a case of the flutters",
"Melyana, your medical skills are as impressive as your mountain climbing",
"Mei-Mei, got any treatments for falling head over heels?",
"Dr. T, your charm's more potent than any medicine",
"Melyana, you scale mountains and my affections with equal ease",
"Mei-Mei, your smile's more refreshing than mountain air",
"Dr. Tanuwijaya, I think I need a check-up for these butterflies",
"Melyana, your healing touch has cured my loneliness",
"Mei-Mei, is your heart rate always this electrifying?",
"Dr. T, your presence is better than any prescription",
"Melyana, you've reached the peak of my admiration",
"Mei-Mei, your energy could power a whole hospital",
"Dr. Tanuwijaya, I'm coming down with a case of the smittens",
"Melyana, your intelligence is as attractive as your hiking stamina",
"Mei-Mei, got any medical advice for a racing heart?",
"Dr. T, your charm should be studied in medical school",
"Melyana, you've conquered the mountain of my affections",
"Mei-Mei, your smile could light up the darkest hiking trail",
"Dr. Tanuwijaya, I might need oxygen after you take my breath away",
"Mei-Mei, your stethoscope must be magic, it's hearing my heartbeat from afar",
"Dr. T, your surgical precision has stitched my heart back together",
"Melyana, you're the GPS to my heart's uncharted territories",
"Mei-Mei, is your medical degree in stealing hearts?",
"Dr. Tanuwijaya, your bedside manner is giving me a fever",
"Melyana, you've scaled the Everest of my affections",
"Mei-Mei, your diagnosis skills are as sharp as your hiking boots",
"Dr. T, I think I need a lifetime prescription of your company",
"Melyana, your smile could cure the common cold",
"Mei-Mei, is your backpack full of stolen hearts?",
"Dr. Tanuwijaya, your charm is more infectious than any virus",
"Melyana, you've mapped the terrain of my heart",
"Mei-Mei, your medical knowledge is as vast as the mountains you climb",
"Dr. T, I think I'm having an allergic reaction to your absence",
"Melyana, your laughter echoes like birdsong on a mountain trail",
"Mei-Mei, got any cures for falling head over hiking boots?",
"Dr. Tanuwijaya, your intelligence is making my neurons fire",
"Melyana, you've reached the summit of my dreams",
"Mei-Mei, your healing touch has mended my broken heart",
"Dr. T, I think I need a referral to the department of your affections",
"Melyana, your charm is as refreshing as a mountain stream",
"Mei-Mei, is your medical bag packed with love potions?",
"Dr. Tanuwijaya, your presence is more soothing than any anesthetic",
"Melyana, you've diagnosed me with a severe case of admiration",
"Mei-Mei, your smile is brighter than any hospital fluorescent",
"Dr. T, I think I need a CAT scan to see if you're on my mind",
"Melyana, your beauty rivals the scenic views of your hikes",
"Mei-Mei, got any medical explanation for these butterflies?",
"Dr. Tanuwijaya, your charm should be bottled and prescribed",
"Melyana, you've navigated straight to my heart",
"Mei-Mei, your bedside manner has my pulse racing",
"Dr. T, I think I'm addicted to your company",
"Melyana, your grace on mountain trails matches your hospital halls",
"Mei-Mei, is your medical coat made of boyfriend material?",
"Dr. Tanuwijaya, your intelligence is my favorite stimulant",
"Melyana, you've scaled the heights of my esteem",
"Mei-Mei, your healing presence is better than any medicine",
"Dr. T, I think I need a second opinion on how amazing you are",
"Melyana, your smile could power a whole hospital wing",
"Mei-Mei, got any treatments for chronic admiration?",
"Dr. Tanuwijaya, your charm is off the medical charts",
"Melyana, you've mapped every contour of my heart",
"Mei-Mei, your medical skills are as impressive as your trail blazing",
"Dr. T, I think I'm developing symptoms of major attraction",
"Melyana, your laughter is more uplifting than any mountain peak",
"Mei-Mei, is your stethoscope picking up the sound of my heart skipping?",
"Dr. Tanuwijaya, your presence is more reviving than any defibrillator",
"Melyana, you've diagnosed my heart with a severe case of the flutters",
"Mei-Mei, your smile is more powerful than any pain reliever",
"Dr. T, I think I need a prescription for more of your time",
"Melyana, your charm could move medical mountains",
"Mei-Mei, got any cures for being hopelessly smitten?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of brain teaser",
"Melyana, you've reached the pinnacle of my affections",
"Mei-Mei, your healing touch has mended my lonely heart",
"Dr. T, I think I need an X-ray to see if you've stolen my heart",
"Melyana, your grace in scrubs matches your trail-blazing spirit",
"Mei-Mei, is your medical bag full of love remedies?",
"Dr. Tanuwijaya, your charm is more potent than any medication",
"Melyana, you've conquered the summit of my admiration",
"Mei-Mei, your bedside manner has my heart rate off the charts",
"Dr. T, I think I'm experiencing side effects of your charisma",
"Melyana, your smile could light up the darkest hospital corridor",
"Mei-Mei, got any medical advice for a heart that won't stop racing?",
"Dr. Tanuwijaya, your presence is more calming than any sedative",
"Melyana, you've diagnosed me with a chronic case of infatuation",
"Mei-Mei, your medical expertise is as breathtaking as mountain vistas",
"Dr. T, I think I need a full workup to understand these feelings",
"Melyana, your charm could revolutionize patient care",
"Mei-Mei, is your lab coat enchanted? You look magical in it",
"Dr. Tanuwijaya, your intelligence is my favorite kind of stimulation",
"Melyana, you've mapped the uncharted territories of my heart",
"Mei-Mei, your healing presence is more effective than any therapy",
"Dr. T, I think I need a referral to the specialist of your affections",
"Melyana, your smile could cure even the toughest medical cases",
"Mei-Mei, got any treatments for an overdose of adoration?",
"Dr. Tanuwijaya, your charm should be studied in medical textbooks",
"Melyana, you've scaled the Everest of my esteem",
"Mei-Mei, your medical intuition is as sharp as your hiking instincts",
"Dr. T, I think I'm developing complications from your attractiveness",
"Melyana, your laughter is more rejuvenating than any vitamin",
"Mei-Mei, is your stethoscope magic? It's hearing my silent admiration",
"Dr. Tanuwijaya, your presence is more healing than any medicine",
"Melyana, you've diagnosed my heart with a terminal case of love",
"Mei-Mei, your smile is more effective than any pain management",
"Dr. T, I think I need a long-term treatment plan of your company",
"Melyana, your charm could solve the toughest medical mysteries",
"Mei-Mei, got any cures for falling irrevocably in love?",
"Dr. Tanuwijaya, your intelligence is my favorite form of brain exercise",
"Melyana, you've reached the zenith of my affections",
"Mei-Mei, your healing touch has revived my weary soul",
"Dr. T, I think I need an MRI to see how deeply you've affected me",
"Melyana, your grace in the OR matches your mountaineering finesse",
"Mei-Mei, is your medical knowledge as vast as your hiking trails?",
"Dr. Tanuwijaya, your charm is more contagious than any virus",
"Melyana, you've conquered the highest peak of my admiration",
"Mei-Mei, your bedside manner has my heart doing cartwheels",
"Dr. T, I think I need a consult for these heart flutters",
"Melyana, your surgical precision extends to matters of the heart",
"Mei-Mei, is your lab coat designer? It accentuates your charm",
"Dr. Tanuwijaya, your bedside manner is giving me good vibrations",
"Melyana, you've mapped a trail straight to my affections",
"Mei-Mei, got any remedies for being head over heels?",
"Dr. T, your presence is more soothing than any therapy session",
"Melyana, your smile outshines even the brightest OR lights",
"Mei-Mei, is your medical bag packed with love elixirs?",
"Dr. Tanuwijaya, your intelligence is my favorite form of stimulation",
"Melyana, you've scaled the highest peak of my esteem",
"Mei-Mei, your healing touch has rejuvenated my spirits",
"Dr. T, I might need an EKG to monitor these heart palpitations",
"Melyana, your grace in scrubs rivals your trail-blazing prowess",
"Mei-Mei, is your stethoscope tuned to the frequency of love?",
"Dr. Tanuwijaya, your charm is more powerful than any placebo",
"Melyana, you've diagnosed me with a severe case of admiration",
"Mei-Mei, your smile is more refreshing than post-hike hydration",
"Dr. T, I think I need a prescription for your undivided attention",
"Melyana, your medical intuition is as sharp as your climbing skills",
"Mei-Mei, got any treatments for chronic daydreaming about you?",
"Dr. Tanuwijaya, your presence is more revitalizing than any IV drip",
"Melyana, you've reached the summit of my deepest affections",
"Mei-Mei, your laughter echoes like a heartbeat in my stethoscope",
"Dr. T, I might need a CT scan to see how you've affected my brain",
"Melyana, your charm could revolutionize patient recovery rates",
"Mei-Mei, is your medical coat infused with irresistible allure?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of challenge",
"Melyana, you've navigated the complex terrain of my heart",
"Mei-Mei, your healing presence is more potent than any antibiotic",
"Dr. T, I think I need a referral to the department of your charms",
"Melyana, your smile could power an entire hospital wing",
"Mei-Mei, got any cures for being utterly enchanted by you?",
"Dr. Tanuwijaya, your bedside manner has my pulse racing overtime",
"Melyana, you've scaled new heights in both medicine and my heart",
"Mei-Mei, is your lab equipment calibrated to measure attraction?",
"Dr. T, your presence is more calming than any sedative",
"Melyana, your surgical skills have stitched my heart back together",
"Mei-Mei, got any medical explanations for these butterflies?",
"Dr. Tanuwijaya, your charm should be studied in clinical trials",
"Melyana, you've mapped every contour of my affections",
"Mei-Mei, your medical expertise is as breathtaking as mountaintops",
"Dr. T, I might need an MRI to see how deeply you've affected me",
"Melyana, your grace in the ER matches your hiking elegance",
"Mei-Mei, is your medical knowledge as vast as your trail network?",
"Dr. Tanuwijaya, your intelligence is my favorite form of therapy",
"Melyana, you've diagnosed my heart with a terminal case of love",
"Mei-Mei, your smile is more effective than any pain management",
"Dr. T, I think I need a long-term treatment plan of your company",
"Melyana, your charm could solve the toughest medical mysteries",
"Mei-Mei, got any cures for falling irrevocably in love?",
"Dr. Tanuwijaya, your presence is more healing than any medicine",
"Melyana, you've reached the zenith of my admiration and respect",
"Mei-Mei, your healing touch has revived my weary soul",
"Dr. T, I might need an X-ray to see if you've stolen my heart",
"Melyana, your medical intuition is as sharp as your trail sense",
"Mei-Mei, is your stethoscope picking up the rhythm of my heart?",
"Dr. Tanuwijaya, your charm is more infectious than any virus",
"Melyana, you've conquered the highest peak of my esteem",
"Mei-Mei, your bedside manner has my heart doing somersaults",
"Dr. T, I think I'm developing complications from your attractiveness",
"Melyana, your laughter is more rejuvenating than any vitamin",
"Mei-Mei, is your medical bag equipped with love potions?",
"Dr. Tanuwijaya, your presence is more revitalizing than any tonic",
"Melyana, you've diagnosed my heart with a chronic case of adoration",
"Mei-Mei, your smile is brighter than the most advanced medical tech",
"Dr. T, I might need a second opinion on how amazing you are",
"Melyana, your charm could power an entire medical research facility",
"Mei-Mei, got any treatments for an overdose of admiration?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of puzzle",
"Melyana, you've mapped the uncharted territories of my affections",
"Mei-Mei, your healing presence is more soothing than any balm",
"Dr. T, I think I need a full workup to understand these feelings",
"Melyana, your surgical precision extends to matters of the heart",
"Mei-Mei, is your lab coat designer? It perfectly complements you",
"Dr. Tanuwijaya, your bedside manner is giving me the good kind of chills",
"Melyana, you've blazed a trail straight to the center of my heart",
"Mei-Mei, got any medical advice for a heart that won't stop racing?",
"Dr. T, your presence is more calming than any meditation session",
"Melyana, your smile outshines even the brightest surgical lights",
"Mei-Mei, is your medical bag packed with irresistible charm?",
"Dr. Tanuwijaya, your intelligence is my favorite form of attraction",
"Melyana, you've scaled the highest peak of my admiration",
"Mei-Mei, your healing touch has rejuvenated my entire being",
"Dr. T, I might need an ECG to monitor these heart flutters",
"Melyana, your grace in the OR matches your trail-blazing elegance",
"Mei-Mei, is your stethoscope tuned to the frequency of adoration?",
"Dr. Tanuwijaya, your charm is more powerful than any treatment",
"Melyana, you've diagnosed me with a severe case of infatuation",
"Mei-Mei, your smile is more refreshing than post-surgery relief",
"Dr. T, I think I need a prescription for your undivided attention",
"Melyana, your medical intuition is as sharp as your climbing instincts",
"Mei-Mei, got any cures for chronic daydreaming about you?",
"Dr. Tanuwijaya, your presence is more revitalizing than any therapy",
"Melyana, you've reached the pinnacle of both medicine and my heart",
"Mei-Mei, your laughter echoes like the sweetest heart monitor beep",
"Dr. T, I might need a brain scan to see how you've affected my mind",
"Melyana, your charm could revolutionize the entire medical field",
"Mei-Mei, is your medical coat infused with an irresistible aura?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of stimulant",
"Melyana, you've navigated the complex landscape of my affections",
"Mei-Mei, your healing presence is more potent than any miracle drug",
"Dr. T, I think I need a referral to the specialist of your charms",
"Melyana, your smile could illuminate the darkest hospital corners",
"Mei-Mei, got any remedies for being utterly spellbound by you?",
"Dr. Tanuwijaya, your bedside manner has my vital signs improving",
"Melyana, you've scaled new heights in both healthcare and my heart",
"Mei-Mei, is your lab equipment calibrated to measure devotion?",
"Dr. T, your presence is more soothing than any pain reliever",
"Melyana, your surgical skills have mended my once-broken heart",
"Mei-Mei, got any medical explanations for these heart somersaults?",
"Dr. Tanuwijaya, your charm should be patented as a medical marvel",
"Melyana, you've mapped every intricate detail of my affections",
"Mei-Mei, your medical expertise is as impressive as your trail skills",
"Dr. T, I might need a full body scan to see your total effect on me",
"Melyana, your grace in the clinic matches your hiking finesse",
"Mei-Mei, is your medical knowledge as deep as the valleys you hike?",
"Dr. Tanuwijaya, your intelligence is my favorite form of medicine",
"Melyana, you've diagnosed my heart with an incurable case of love",
"Mei-Mei, your smile is more effective than any anesthetic",
"Dr. T, I think I need a lifetime supply of your healing presence",
"Melyana, your charm could unravel the most complex medical enigmas",
"Mei-Mei, got any treatments for an extreme case of admiration?",
"Dr. Tanuwijaya, your presence is more curative than any procedure",
"Melyana, you've reached the apex of both medical skill and allure",
"Mei-Mei, your healing touch has breathed new life into my world",
"Dr. T, I might need a cardiology consult to handle these feelings",
"Melyana, your medical intuition is as keen as your trail sense",
"Mei-Mei, is your stethoscope attuned to the melody of my heart?",
"Dr. Tanuwijaya, your charm is more captivating than any case study",
"Melyana, you've conquered the steepest climb to my affections",
"Mei-Mei, your bedside manner has my recovery rate skyrocketing",
"Dr. T, I think I'm experiencing side effects of your magnetic charm",
"Melyana, your laughter is more healing than any physical therapy",
"Mei-Mei, is your medical kit equipped with love elixirs?",
"Dr. Tanuwijaya, your presence is more invigorating than any vitamin",
"Melyana, you've diagnosed my heart with chronic blissful palpitations",
"Mei-Mei, your smile outshines the most advanced medical equipment",
"Dr. T, I might need a specialist to explain these intense feelings",
"Melyana, your charm could fuel groundbreaking medical research",
"Mei-Mei, got any prescriptions for an overdose of infatuation?",
"Dr. Tanuwijaya, your intelligence is my favorite form of challenge",
"Melyana, you've mapped the intricate pathways of my devotion",
"Mei-Mei, your healing aura is more potent than any wonder drug",
"Dr. T, I think I need a thorough examination of these emotions",
"Melyana, your surgical finesse extends to matters of the heart",
"Mei-Mei, is your lab coat tailored to enhance your natural charm?",
"Dr. Tanuwijaya, your bedside manner is giving me pleasant shivers",
"Melyana, you've pioneered a direct route to the core of my heart",
"Mei-Mei, got any medical insights on this accelerated heartbeat?",
"Dr. T, your presence is more relaxing than any therapeutic massage",
"Melyana, your smile outperforms the brightest medical imaging tech",
"Mei-Mei, is your medical arsenal stocked with irresistible allure?",
"Dr. Tanuwijaya, your intelligence is my preferred form of attraction",
"Melyana, you've ascended to the highest summit of my admiration",
"Mei-Mei, your healing touch has rejuvenated my entire existence",
"Dr. T, I might need continuous monitoring for these heart flutters",
"Melyana, your poise in the hospital parallels your hiking grace",
"Mei-Mei, is your stethoscope calibrated to the rhythm of devotion?",
"Dr. Tanuwijaya, your charm surpasses the potency of any medication",
"Melyana, you've diagnosed me with an acute case of adoration",
"Mei-Mei, your smile is more revitalizing than post-op recovery",
"Dr. T, I think I require a lifetime prescription of your company",
"Melyana, your medical acumen is as sharp as your mountaineering skills",
"Mei-Mei, got any remedies for persistent thoughts about you?",
"Dr. Tanuwijaya, your presence outperforms any therapeutic regimen",
"Melyana, you've attained the zenith in both medicine and my heart",
"Mei-Mei, your laughter resonates like the most reassuring vital sign",
"Dr. T, I might need neurological testing to gauge your impact on me",
"Melyana, your charm could inspire a new era in medical science",
"Mei-Mei, is your medical attire imbued with an enchanting essence?",
"Dr. Tanuwijaya, your intellect is my preferred cognitive enhancer",
"Melyana, you've skillfully navigated the intricate maze of my affection",
"Mei-Mei, your healing influence surpasses any known medical treatment",
"Dr. T, I think I need a consultation with the expert of your charms",
"Melyana, your smile could illuminate the most state-of-the-art OR",
"Mei-Mei, got any cures for being completely captivated by you?",
"Dr. Tanuwijaya, your patient care has my health markers improving",
"Melyana, you've pioneered new frontiers in healthcare and my heart",
"Mei-Mei, is your medical equipment fine-tuned to measure adoration?",
"Dr. T, your presence surpasses the efficacy of any painkiller",
"Melyana, your clinical expertise has mended my longing heart",
"Mei-Mei, got any medical theories for these emotional cartwheels?",
"Dr. Tanuwijaya, your charisma deserves its own medical journal",
"Melyana, you've precisely mapped every nuance of my affections",
"Mei-Mei, your medical prowess rivals your impressive trail expertise",
"Dr. T, I might need a comprehensive scan to assess your full impact",
"Melyana, your hospital demeanor mirrors your mountaineering poise",
"Mei-Mei, does your medical wisdom run as deep as the trails you love?",
"Dr. Tanuwijaya, your intelligence is my most effective treatment",
"Melyana, you've diagnosed my heart with perpetual infatuation",
"Mei-Mei, your smile outperforms even the most advanced pain relief",
"Dr. T, I think I need an endless supply of your healing presence",
"Melyana, your charm could decode the most baffling medical mysteries",
"Mei-Mei, got any treatments for an extreme case of heart eyes?",
"Dr. Tanuwijaya, your presence is more beneficial than any procedure",
"Melyana, you've achieved the pinnacle of medical skill and charisma",
"Mei-Mei, your healing touch has transformed my entire perspective",
"Dr. T, I might need a cardiac specialist to manage these feelings",
"Melyana, your clinical intuition matches your impeccable trail sense",
"Mei-Mei, is your stethoscope tuned to the symphony of my heartbeat?",
"Dr. Tanuwijaya, your charm is more engaging than any medical text",
"Melyana, you've conquered the most challenging ascent to my heart",
"Mei-Mei, your patient care has my recovery graph off the charts",
"Dr. T, I think I'm experiencing positive side effects from your charm",
"Melyana, your laughter is more therapeutic than any rehab session",
"Mei-Mei, is your medical kit stocked with love-inducing remedies?",
"Dr. Tanuwijaya, your presence is more energizing than any supplement",
"Melyana, you've diagnosed my heart with perpetual joyful palpitations",
"Mei-Mei, your smile outshines even the most advanced medical tech",
"Dr. T, I might need an expert consult to explain these intense feelings",
"Melyana, your charisma could revolutionize medical breakthroughs",
"Mei-Mei, got any prescriptions for an overdose of heart flutters?",
"Dr. Tanuwijaya, your intellect is my favorite form of mental exercise",
"Melyana, you've expertly mapped the complex terrain of my devotion",
"Mei-Mei, your healing presence surpasses any miracle treatment",
"Dr. T, I think I need a thorough analysis of these heartfelt emotions",
"Melyana, your surgical precision extends to matters of the soul",
"Mei-Mei, is your lab coat designed to enhance your natural magnetism?",
"Dr. Tanuwijaya, your bedside manner gives me the best kind of chills",
"Melyana, you've blazed a trail of affection right to my core",
"Mei-Mei, is your medical degree in stealing hearts?",
"Dr. T, your diagnostic skills have uncovered my hidden feelings",
"Melyana, you're the perfect blend of trail mix and medical expertise",
"Mei-Mei, your bedside manner is giving me a chronic case of the swoons",
"Dr. Tanuwijaya, I think I need a prescription for your undivided attention",
"Melyana, your smile is more effective than any defibrillator",
"Mei-Mei, got any treatments for an overactive heart around you?",
"Dr. T, your charm is more infectious than any virus I've studied",
"Melyana, you've scaled the Everest of my affections with ease",
"Mei-Mei, is your stethoscope picking up these lovestruck rhythms?",
"Dr. Tanuwijaya, your intelligence is my favorite form of stimulation",
"Melyana, you've diagnosed me with a severe case of admiration",
"Mei-Mei, your healing touch has cured my loneliness",
"Dr. T, I think I need an MRI to see how deeply you've affected me",
"Melyana, your grace in scrubs rivals your mountaineering finesse",
"Mei-Mei, is your medical bag equipped with love potions?",
"Dr. Tanuwijaya, your presence is more soothing than any anesthetic",
"Melyana, you've reached the summit of both medicine and my heart",
"Mei-Mei, your laughter echoes like the sweetest heart monitor beep",
"Dr. T, I might need a CT scan to see how you've rewired my brain",
"Melyana, your charm could revolutionize patient recovery rates",
"Mei-Mei, is your lab coat infused with an irresistible allure?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of puzzle",
"Melyana, you've navigated the complex terrain of my affections",
"Mei-Mei, your healing presence is more potent than any antibiotic",
"Dr. T, I think I need a referral to the specialist of your charms",
"Melyana, your smile could power an entire hospital wing",
"Mei-Mei, got any cures for being utterly enchanted by you?",
"Dr. Tanuwijaya, your bedside manner has my vital signs improving",
"Melyana, you've scaled new heights in both healthcare and my heart",
"Mei-Mei, is your medical equipment calibrated to measure devotion?",
"Dr. T, your presence is more revitalizing than any IV drip",
"Melyana, your surgical skills have stitched my heart back together",
"Mei-Mei, got any medical explanations for these butterflies?",
"Dr. Tanuwijaya, your charm should be studied in clinical trials",
"Melyana, you've mapped every contour of my deepest affections",
"Mei-Mei, your medical expertise is as breathtaking as mountain vistas",
"Dr. T, I might need an X-ray to see if you've stolen my heart",
"Melyana, your grace in the ER matches your trail-blazing elegance",
"Mei-Mei, is your medical knowledge as vast as your hiking trails?",
"Dr. Tanuwijaya, your intelligence is my favorite form of therapy",
"Melyana, you've diagnosed my heart with a terminal case of love",
"Mei-Mei, your smile is more effective than any pain management",
"Dr. T, I think I need a long-term treatment plan of your company",
"Melyana, your charm could solve the most complex medical mysteries",
"Mei-Mei, got any cures for falling irrevocably in love?",
"Dr. Tanuwijaya, your presence is more healing than any medicine",
"Melyana, you've reached the zenith of my admiration and respect",
"Mei-Mei, your healing touch has revived my weary soul",
"Dr. T, I might need an EKG to monitor these persistent heart flutters",
"Melyana, your medical intuition is as sharp as your trail sense",
"Mei-Mei, is your stethoscope picking up the rhythm of my heart?",
"Dr. Tanuwijaya, your charm is more infectious than any known pathogen",
"Melyana, you've conquered the highest peak of my esteem",
"Mei-Mei, your bedside manner has my heart doing somersaults",
"Dr. T, I think I'm developing complications from your attractiveness",
"Melyana, your laughter is more rejuvenating than any vitamin",
"Mei-Mei, is your medical bag equipped with love elixirs?",
"Dr. Tanuwijaya, your presence is more revitalizing than any tonic",
"Melyana, you've diagnosed my heart with a chronic case of adoration",
"Mei-Mei, your smile is brighter than the most advanced medical tech",
"Dr. T, I might need a second opinion on how amazing you are",
"Melyana, your charm could power an entire medical research facility",
"Mei-Mei, got any treatments for an overdose of admiration?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of challenge",
"Melyana, you've mapped the uncharted territories of my affections",
"Mei-Mei, your healing presence is more soothing than any balm",
"Dr. T, I think I need a full workup to understand these feelings",
"Melyana, your surgical precision extends to matters of the heart",
"Mei-Mei, is your lab coat designer? It perfectly complements you",
"Dr. Tanuwijaya, your bedside manner is giving me the good kind of chills",
"Melyana, you've blazed a trail straight to the center of my heart",
"Mei-Mei, got any medical advice for a heart that won't stop racing?",
"Dr. T, your presence is more calming than any meditation session",
"Melyana, your smile outshines even the brightest surgical lights",
"Mei-Mei, is your medical bag packed with irresistible charm?",
"Dr. Tanuwijaya, your intelligence is my favorite form of attraction",
"Melyana, you've scaled the highest peak of my admiration",
"Mei-Mei, your healing touch has rejuvenated my entire being",
"Dr. T, I might need an ECG to monitor these persistent heart flutters",
"Melyana, your grace in the OR matches your trail-blazing elegance",
"Mei-Mei, is your stethoscope tuned to the frequency of adoration?",
"Dr. Tanuwijaya, your charm is more powerful than any treatment",
"Melyana, you've diagnosed me with a severe case of infatuation",
"Mei-Mei, your smile is more refreshing than post-surgery relief",
"Dr. T, I think I need a prescription for your undivided attention",
"Melyana, your medical intuition is as sharp as your climbing instincts",
"Mei-Mei, got any cures for chronic daydreaming about you?",
"Dr. Tanuwijaya, your presence is more revitalizing than any therapy",
"Melyana, you've reached the pinnacle of both medicine and my heart",
"Mei-Mei, your laughter echoes like the sweetest heart monitor beep",
"Dr. T, I might need a brain scan to see how you've affected my mind",
"Melyana, your charm could revolutionize the entire medical field",
"Mei-Mei, is your medical coat infused with an irresistible aura?",
"Dr. Tanuwijaya, your intelligence is my favorite kind of stimulant",
"Melyana, you've navigated the complex landscape of my affections",
"Mei-Mei, your healing presence is more potent than any miracle drug",
"Dr. T, I think I need a referral to the specialist of your charms",
"Melyana, your smile could illuminate the darkest hospital corners",
"Mei-Mei, got any remedies for being utterly spellbound by you?",
"Dr. Tanuwijaya, your bedside manner has my vital signs improving",
"Melyana, you've scaled new heights in both healthcare and my heart",
"Mei-Mei, is your lab equipment calibrated to measure devotion?",
"Dr. T, your presence is more soothing than any pain reliever",
"Melyana, your surgical skills have mended my once-broken heart",
"Mei-Mei, got any medical explanations for these heart somersaults?",
"Dr. Tanuwijaya, your charm should be patented as a medical marvel",
"Melyana, you've mapped every intricate detail of my affections",
"Mei-Mei, your medical expertise is as impressive as your trail skills",
"Dr. T, I might need a full body scan to see your total effect on me",
"Melyana, your grace in the clinic matches your hiking finesse",
"Mei-Mei, is your medical knowledge as deep as the valleys you hike?",
"Dr. Tanuwijaya, your intelligence is my favorite form of medicine",
"Melyana, you've diagnosed my heart with an incurable case of love",
"Mei-Mei, your smile is more effective than any anesthetic",
"Dr. T, I think I need a lifetime supply of your healing presence",
"Melyana, your charm could unravel the most complex medical enigmas",
"Mei-Mei, got any treatments for an extreme case of admiration?",
"Dr. Tanuwijaya, your presence is more curative than any procedure",
"Melyana, you've reached the apex of both medical skill and allure",
"Mei-Mei, your healing touch has breathed new life into my world",
"Dr. T, I might need a cardiology consult to handle these feelings",
"Melyana, your medical intuition is as keen as your trail sense",
"Mei-Mei, is your stethoscope attuned to the melody of my heart?",
"Dr. Tanuwijaya, your charm is more captivating than any case study",
"Melyana, you've conquered the steepest climb to my affections",
"Mei-Mei, your bedside manner has my recovery rate skyrocketing",
"Dr. T, I think I'm experiencing side effects of your magnetic charm",
"Melyana, your laughter is more healing than any physical therapy",
"Mei-Mei, is your medical kit equipped with love elixirs?",
"Dr. Tanuwijaya, your presence is more invigorating than any vitamin",
"Melyana, you've diagnosed my heart with chronic blissful palpitations",
"Mei-Mei, your smile outshines the most advanced medical equipment",
"Dr. T, I might need a specialist to explain these intense feelings",
"Melyana, your charm could fuel groundbreaking medical research",
"Mei-Mei, got any prescriptions for an overdose of infatuation?",
"Dr. Tanuwijaya, your intelligence is my favorite form of challenge",
"Melyana, you've mapped the intricate pathways of my devotion",
"Mei-Mei, your healing aura is more potent than any wonder drug",
"Dr. T, I think I need a thorough examination of these emotions",
"Melyana, your surgical finesse extends to matters of the heart",
"Mei-Mei, is your lab coat tailored to enhance your natural charm?",
"Dr. Tanuwijaya, your bedside manner is giving me pleasant shivers",
"Melyana, you've pioneered a direct route to the core of my heart",
"Mei-Mei, got any medical insights on this accelerated heartbeat?",
"Dr. T, your presence is more relaxing than any therapeutic massage",
"Melyana, your smile outperforms the brightest medical imaging tech",
"Mei-Mei, is your medical arsenal stocked with irresistible allure?",
"Dr. Tanuwijaya, your intelligence is my preferred form of attraction",
"Melyana, you've ascended to the highest summit of my admiration",
"Mei-Mei, your healing touch has rejuvenated my entire existence",
"Dr. T, I might need continuous monitoring for these heart flutters",
"Melyana, your poise in the hospital parallels your hiking grace",
"Mei-Mei, is your stethoscope calibrated to the rhythm of devotion?",
"Dr. Tanuwijaya, your charm surpasses the potency of any medication",
"Melyana, you've diagnosed me with an acute case of adoration",
"Mei-Mei, your smile is more revitalizing than post-op recovery",
"Dr. T, I think I require a lifetime prescription of your company",
"Melyana, your medical acumen is as sharp as your mountaineering skills",
"Mei-Mei, got any remedies for persistent thoughts about you?",
"Dr. Tanuwijaya, your presence outperforms any therapeutic regimen",
"Melyana, you've attained the zenith in both medicine and my heart",
"Mei-Mei, your laughter resonates like the most reassuring vital sign",
"Dr. T, I might need neurological testing to gauge your impact on me",
"Melyana, your charm could inspire a new era in medical science",
"Mei-Mei, is your medical attire imbued with an enchanting essence?",
"Dr. Tanuwijaya, your intellect is my preferred cognitive enhancer",
"Melyana, you've skillfully navigated the intricate maze of my affection",
"Mei-Mei, your healing influence surpasses any known medical treatment",
"Dr. T, I think I need a consultation with the expert of your charms",
"Melyana, your smile could illuminate the most state-of-the-art OR",
"Mei-Mei, got any cures for being completely captivated by you?",
"Dr. Tanuwijaya, your patient care has my health markers improving",
"Melyana, you've pioneered new frontiers in healthcare and my heart",
"Mei-Mei, is your medical equipment fine-tuned to measure adoration?",
"Dr. T, your presence surpasses the efficacy of any painkiller",
"Melyana, your clinical expertise has mended my longing heart",
"Mei-Mei, got any medical theories for these emotional cartwheels?",
"Dr. Tanuwijaya, your charisma deserves its own medical journal",
"Melyana, you've precisely mapped every nuance of my affections",
"Mei-Mei, your medical prowess rivals your impressive trail expertise",
"Dr. T, I might need a comprehensive scan to assess your full impact",
"Melyana, your hospital demeanor mirrors your mountaineering poise",
"Mei-Mei, does your medical wisdom run as deep as the trails you love?",
"Dr. Tanuwijaya, your intelligence is my most effective treatment",
"Melyana, you've diagnosed my heart with perpetual infatuation",
"Mei-Mei, your smile outperforms even the most advanced pain relief",
"Dr. T, I think I need an endless supply of your healing presence",
"Melyana, your charm could decode the most baffling medical mysteries",
"Mei-Mei, got any treatments for an extreme case of heart eyes?",
"Dr. Tanuwijaya, your presence is more beneficial than any procedure",
"Melyana, you've achieved the pinnacle of medical skill and charisma",
"Mei-Mei, your healing touch has transformed my entire perspective",
"Dr. T, I might need a cardiac specialist to manage these feelings",
"Melyana, your clinical intuition matches your impeccable trail sense",
"Mei-Mei, is your stethoscope tuned to the symphony of my heartbeat?",
"Dr. Tanuwijaya, your charm is more engaging than any medical text",
"Melyana, you've conquered the most challenging ascent to my heart",
"Mei-Mei, your patient care has my recovery graph off the charts",
"Dr. T, I think I'm experiencing positive side effects from your charm",
"Melyana, your laughter is more therapeutic than any rehab session",
"Mei-Mei, is your medical kit stocked with love-inducing remedies?",
"Dr. Tanuwijaya, your presence is more energizing than any supplement",
"Melyana, you've diagnosed my heart with perpetual joyful palpitations",
"Mei-Mei, your smile outshines even the most advanced medical tech",
"Dr. T, I might need an expert consult to explain these intense feelings",
"Melyana, your charisma could revolutionize medical breakthroughs",

};

#define ADVICE_COUNT (sizeof(advice_list) / sizeof(advice_list[0]))
